apiVersion: apps/v1
kind: Deployment
metadata:
  name: rural-education-deployment
  labels:
    app: rural-education
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rural-education
  template:
    metadata:
      labels:
        app: rural-education
    spec:
      containers:
        - name: rural-education
          image: bhagyasree0506/rural-education:latest  # Jenkins will replace with commit tag
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
