apiVersion: apps/v1
kind: Deployment
metadata:
  name: rural-education-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rural-education
  template:
    metadata:
      labels:
        app: rural-education
    spec:
      containers:
      - name: rural-education-container
        image: bhagyasree0506/rural-education:latest
        ports:
        - containerPort: 80
